name: ✨ 新需求（组件 / 页面 / 功能）
description: 用于提交新功能、页面或组件的开发请求
title: "[Feature]: "
labels: 
  - enhancement
  - needs-triages

body:
  - type: dropdown
    id: feature_type
    attributes:
      label: 需求类型
      description: 请选择你要提交的内容类型
      options:
        - 新组件（Component）
        - 新页面（Page）
        - 新功能（Feature）
        - 其他
    validations:
      required: true

  - type: input
    id: summary
    attributes:
      label: 简要描述
      description: 简洁说明你想添加什么功能
      placeholder: 比如：“添加一个支持多选的 TagSelector 组件”
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: 功能需求与说明
      description: 请列出你对功能的具体要求（支持哪些功能、边界情况等）
      placeholder: |
        - 支持自定义选项列表
        - 支持禁用某些项
        - 可传入默认选中值
    validations:
      required: false

  - type: input
    id: design_link
    attributes:
      label: 设计稿 / 原型链接（可选）
      placeholder: 比如 Figma、Sketch、截图链接
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 其他补充信息
      placeholder: 例如：是否影响现有模块、性能要求、联动模块等
    validations:
      required: false
