import type { Metadata } from "next";

import "@/styles/global.scss"

import ThemeProvider from "@/common/theme/ThemeProvider";
import MainLayout from "@/components/layout/Main";
import "../styles/theme.scss"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <MainLayout>
            {children}
          </MainLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
